
package trng.soap.service.loan;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "LoanService", targetNamespace = "http://www.trng.org/LoanService/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoanService {


    /**
     * 
     * @param request
     * @return
     *     returns trng.soap.service.loan.ProcessLoanResponse
     */
    @WebMethod(action = "http://www.trng.org/LoanService/processLoan")
    @WebResult(name = "processLoanResponse", targetNamespace = "http://www.trng.org/LoanService/", partName = "response")
    public ProcessLoanResponse processLoan(
        @WebParam(name = "processLoanRequest", targetNamespace = "http://www.trng.org/LoanService/", partName = "request")
        ProcessLoanRequest request);

}
