
package trng.soap.service.loan;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "LoanService", targetNamespace = "http://www.trng.org/LoanService/", wsdlLocation = "file:/Users/sourabhsp/Documents/workspace-sts-3.8.4.RELEASE/SoapApp/src/main/resources/LoanService.wsdl")
public class LoanService_Service
    extends Service
{

    private final static URL LOANSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(trng.soap.service.loan.LoanService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = trng.soap.service.loan.LoanService_Service.class.getResource(".");
            url = new URL(baseUrl, "file:/Users/sourabhsp/Documents/workspace-sts-3.8.4.RELEASE/SoapApp/src/main/resources/LoanService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/Users/sourabhsp/Documents/workspace-sts-3.8.4.RELEASE/SoapApp/src/main/resources/LoanService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        LOANSERVICE_WSDL_LOCATION = url;
    }

    public LoanService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoanService_Service() {
        super(LOANSERVICE_WSDL_LOCATION, new QName("http://www.trng.org/LoanService/", "LoanService"));
    }

    /**
     * 
     * @return
     *     returns LoanService
     */
    @WebEndpoint(name = "LoanServiceSOAP")
    public LoanService getLoanServiceSOAP() {
        return super.getPort(new QName("http://www.trng.org/LoanService/", "LoanServiceSOAP"), LoanService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoanService
     */
    @WebEndpoint(name = "LoanServiceSOAP")
    public LoanService getLoanServiceSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.trng.org/LoanService/", "LoanServiceSOAP"), LoanService.class, features);
    }

}
